version: '3'
services:
  app:
    image: nginx:alpine
    container_name: unFollow-nodejs
    working_dir: /app
    volumes:
      - ./server.js:/app/server.js
      - ./dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    ports:
      - "8181:80"
      - "8182:443"
    command: >
      sh -c "apk add --no-cache nodejs npm &&
             echo '{\"type\": \"module\"}' > package.json &&
             npm install express axios dotenv &&
             node server.js & nginx -g 'daemon off;'"
    networks:
      - nostream

networks:
  nostream:
    external: true
